### ISSUE TITLE
Trouble building with gradle 4.7 

### ISSUE THREAD

**Issue by minghia** [HanSolo/Enzo#12]
Hi there,
  I trying to build on Centos 6 with gradle 4.7 and for some reason the buildscript part of build.gradle is raising an exception and printing out an error message even though the file pointed to by ${ext.javafxJar} exists and is readable. Any thoughts

Tony

**Comment by HanSolo** [comment]
Will take a look at it as soon as I‘ll be back home again from vacation

**Comment by minghia** [comment]
I fixed by changing classpath files ( ext.javafxJar) to classpath files (${ext.javafxJar}). This causes it to fail elsewhere. I found your area on bitbucket. Is there anyway to shrink the vumeter down in size? There seems to be only one size.

**Comment by HanSolo** [comment]
Current version on bitbucket should now build with gradle 4.7 (commit: fdbdbdb20d67cc7f652dbbadac93e2271)
