### ISSUE TITLE
VU meter unable to scale.

### ISSUE THREAD

**Issue by minghia** [HanSolo/Enzo#13]
I have need for a smaller 7 segment VU meter and it appears that I can't scale it smaller than what the library has calculated the smallest size to be.

**Comment by minghia** [comment]
I have worked out how to make them the right size by scaling them in my FXML file. Is there a way to set the sections from the FXML file?

**Comment by HanSolo** [comment]
To be honest I don't use fxml but as far as I remember I've added a constructor that takes all parameters which should make it possible to set the sections from FXML. But to find that out I also have to test it myself.

**Comment by minghia** [comment]
Thanks for that. What tokens do I use or should I just look at the code?

**Comment by HanSolo** [comment]
Guess you have to take a look at the code cause I'm quite busy these days...sorry

**Comment by minghia** [comment]
That's okay. Thanks for providing the library. It saved me some heavy lifting.
